---
pgsql_yum_repo_baseurl: "http://download.postgresql.org/pub/repos/yum/14/redhat/rhel-{{ ansible_facts['distribution_major_version'] }}-{{ ansible_facts['architecture'] }}/"
pgsql_service_name: postgresql-14.service
pgsql_init_cmd: postgresql-14-setup initdb
pgsql_path_to_hba_conf: /var/lib/pgsql/14/data/pg_hba.conf
pgsql_app_dbname: rest-crud
pgsql_app_user: restcrud
pgsql_app_user_password: restcrud
