galaxy_info:
  role_name: quarkus
  namespace: middleware_automation
  author: Romain Pelisse
  description: Install ...
  company: Red Hat, Inc.

  license: Apache License 2.0

  min_ansible_version: "2.9"

  platforms:
   - name: EL
     versions:
     - 8

  galaxy_tags:
    - quarkus
    - redhat
    - rhel
    - tools
    - application
    - java
