---
- name: "Ensure sudo package name is defined."
  ansible.builtin.set_fact:
    sudo_pkg_name: 'sudo'
  when:
    - not sudo_pkg_name is defined

- name: "Ensure {{ sudo_pkg_name }} is installed (if user is root)."
  ansible.builtin.yum:
    name: "{{ sudo_pkg_name }}"
  when:
    - ansible_user_id == 'root'

- name: Gather the package facts
  ansible.builtin.package_facts:
    manager: auto

- name: "Check if {{ sudo_pkg_name }} is installed."
  ansible.builtin.assert:
    that:
      - sudo_pkg_name in ansible_facts.packages

- name: "Ensure required packages are installed."
  ansible.builtin.yum:
    name:
      - git
      - procps-ng
    state: present

- name: Display Ansible version
  ansible.builtin.debug:
    msg: "Ansible version is {{ ansible_version.full }}, running with Python {{ ansible_python_version }}."
