---
- name: "Ensure sudo package name is defined."
  ansible.builtin.set_fact:
    sudo_pkg_name: 'sudo'
  when:
    - not sudo_pkg_name is defined

- name: "Ensure {{ sudo_pkg_name }} is installed (if user is root)."
  ansible.builtin.dnf:
    name: "{{ sudo_pkg_name }}"
    state: present
  vars:
    ansible_python_interpreter: /usr/bin/python3
  when:
    - ansible_facts['user_id'] == 'root'

- name: "Ensure required packages are installed."
  become: yes
  become_user: root
  ansible.builtin.dnf:
    name:
      - git
      - procps-ng
    state: present
  vars:
    ansible_python_interpreter: /usr/bin/python3
