---
- name: Prepare
  hosts: all
  vars_files:
    - pgsql/vars.yml
  tasks:
    - name: "Ensure common prepare steps are executed."
      ansible.builtin.include_tasks: ../common.yml

    - name: "Set up DB required by ToDo app"
      ansible.builtin.include_tasks: pgsql/set_up.yml

    - name: Display Ansible version
      ansible.builtin.debug:
        msg: "Ansible version is  {{ ansible_version.full }}"
