---
- name: Validation
  hosts: all
  tasks:
    - name: "Verify that app is responding"
      ansible.builtin.include_role:
        name: quarkus
        tasks_from: validate_deployment.yml
      vars:
        quarkus_app_validation_paths:
          - { path: /api }
