---
- name: "Ensure requirements are fullfilled."
  become: True
  block:
    - name: "Ensure required OpenJDK is installed on target."
      ansible.builtin.package:
        name: "{{ quarkus_openjdk_package_version }}"
        state: present
      when:
        - quarkus_openjdk_package_version is defined

    - name: "Ensure Quarkus system group exists on target system"
      ansible.builtin.group:
        name: "{{ quarkus_app_group }}"
      when:
        - quarkus_app_group is defined

    - name: "Ensure Quarkus user exists on target system."
      ansible.builtin.user:
        name: "{{ quarkus_app_user }}"
      when:
        - quarkus_app_user is defined
