---
- name: Prepare
  hosts: all
  tasks:

    - name: "Ensure required packages are installed."
      ansible.builtin.yum:
        name:
          - git
          - procps-ng
          - sudo
        state: present

    - name: Display Ansible version
      ansible.builtin.debug:
        msg: "Ansible version is  {{ ansible_version.full }}"
