---
- name: "Ensure target node is supported."
  ansible.builtin.include_tasks: target_supported.yml

- name: "Ensure required parameters are provided."
  ansible.builtin.assert:
    that:
      - quarkus_builder_host is defined
      - quarkus_app_repo_url is defined
      - quarkus_app_workdir is defined
    quiet: true

- name: "Ensure Maven is installed on builder (if app not using mvnw)"
  ansible.builtin.include_tasks: mvn.yml

- name: "Build app from {{ quarkus_app_repo_url }} on '{{ quarkus_builder_host }}'."
  delegate_to: "{{ quarkus_builder_host }}"
  block:
    - name: "Ensure Java is properly installed"
      ansible.builtin.include_tasks: java.yml

    - name: "Delete previous workdir (if requested)."
      ansible.builtin.file:
        path: "{{ quarkus_app_workdir }}"
        state: absent
      changed_when: false
      when:
        - quarkus_build_delete_workdir is defined
        - quarkus_build_delete_workdir

    - name: "Ensure app workdir exists: {{ quarkus_app_workdir }}"
      become: "{{ quarkus_app_dir_requires_become }}"
      become_user: "{{ quarkus_app_dir_become_user }}"
      ansible.builtin.file:
        path: "{{ quarkus_app_workdir }}"
        owner: "{{ quarkus_app_builder_user | default(omit) }}"
        group: "{{ quarkus_app_builder_group | default(omit) }}"
        mode: 0755
        state: directory

    - name: "Checkout the application source code."
      become: "{{ quarkus_app_builder_user_requires_become }}"
      become_user: "{{ quarkus_app_builder_user }}"
      ansible.builtin.git:
        repo: "{{ quarkus_app_repo_url }}"
        dest: "{{ quarkus_app_workdir }}"
        version: "{{ app_tag | default(omit) }}"
      when:
        - quarkus_app_repo_url is defined and quarkus_app_repo_url

    - name: "Load metadata on source directory"
      ansible.builtin.stat:
        path: "{{ quarkus_app_workdir }}"
      register: source_dir

    - name: "Ensure that source dir exists"
      ansible.builtin.assert:
        that:
          - source_dir is defined and source_dir.stat is defined
          - source_dir.stat.exists is defined and source_dir.stat.exists
        quiet: True
        fail_msg: "The root folder of the Quarkus project does not exits: {{ quarkus_app_workdir }}"

    - name: "Build the App using Maven using {{ quarkus_java_home }} as JAVA_HOME."
      become: "{{ quarkus_app_dir_requires_become }}"
      become_user: "{{ quarkus_app_dir_become_user }}"
      ansible.builtin.command: "{{ quarkus_build_shell_interpreter }} {{ path_to_mvn }} {{ quarkus_maven_build_opts }} package"
      register: mvn_build
      environment:
        JAVA_HOME: "{{ quarkus_java_home }}"
      args:
        chdir: "{{ quarkus_app_workdir }}/{{ quarkus_app_source_folder | default('') }}"
      changed_when: false

    - name: "Display build application log"
      ansible.builtin.debug:
        var: mvn_build.stdout
      when:
        - display_mvn_output is defined
