---
- name: "Ensure target node is supported."
  ansible.builtin.include_tasks: target_supported.yml

- name: "Ensure required parameters are provided."
  ansible.builtin.assert:
    that:
      - quarkus_app_workdir is defined
      - quarkus_path_to_folder_to_deploy is defined
      - app_name is defined
    quiet: true

- name: "Ensure requirements on target system are fullfilled."
  ansible.builtin.include_tasks: deploy/prereqs.yml

- name: "Ensure deployement directory exists: {{ quarkus_path_to_folder_to_deploy }}."
  become: "{{ quarkus_path_to_folder_to_deploy_requires_become }}"
  become_user: "{{ quarkus_path_to_folder_to_deploy_become_user }}"
  ansible.builtin.file:
    path: "{{ quarkus_path_to_folder_to_deploy }}"
    state: directory
    owner: "{{ quarkus_app_user | default(omit) }}"
    group: "{{ quarkus_app_group | default(omit) }}"
    mode: 0755

- name: "Set Quarkus app source dir (if not defined)."
  ansible.builtin.set_fact:
    quarkus_app_src_dir: "{{ quarkus_app_workdir }}/{{ quarkus_app_source_folder | default('') }}/{{ quarkus_build_relative_path_to_deploy_dir }}/"
  when:
    - not quarkus_app_src_dir is defined

- name: "Deploy application as a systemd service on target system."
  ansible.builtin.include_tasks: deploy/main.yml

- name: "Ensure firewalld configuration is appropriate (if requested)."
  ansible.builtin.include_tasks: deploy/firewalld.yml
  when:
    - quarkus_app_firewalld_enabled is defined and quarkus_app_firewalld_enabled

- name: "Verify that deployment is functional."
  ansible.builtin.include_tasks: validate_deployment.yml
  when:
    - quarkus_app_validate_deployment is defined and quarkus_app_validate_deployment
