---
- name: "Ensure that builder host has the appropriate JDK installed: {{ quarkus_java_package_version }}"
  ansible.builtin.dnf:
    name: "{{ quarkus_java_package_version }}"
    state: present
  become: true
  when:
    - quarkus_app_builder_skip_install_java_package is defined and not quarkus_app_builder_skip_install_java_package
    - quarkus_java_package_version is defined and quarkus_java_package_version | length > 0

- name: "Ensure that JAVA_HOME exists: {{ quarkus_java_home }}"
  ansible.builtin.include_tasks: path_exists.yml
  vars:
    quarkus_path_to_file: "{{ quarkus_java_home }}"
    quarkus_file_isdir: "{{ quarkus_java_home_isdir }}"
    quarkus_file_islnk: "{{ quarkus_java_home_islnk }}"

- name: "Ensure that  exists and is executable"
  ansible.builtin.include_tasks: path_exists.yml
  loop:
    - javac
    - java
  loop_control:
    loop_var: quarkus_java_utility
  vars:
    quarkus_path_to_file: "{{ quarkus_java_home }}/bin/{{ quarkus_java_utility }}"
    quarkus_file_isexec: True
