---
- name: "App building uses mvnw."
  when:
    - quarkus_use_mvnw is defined and quarkus_use_mvnw
  block:
    - name: "Ensure required parameters are provided"
      ansible.builtin.assert:
        that:
          - quarkus_app_workdir is defined and quarkus_app_workdir | length > 0
        quiet: True
        fail_msg: "So set path to mvnw the quarkus_app_workdir is required."

    - name: "Set full path to mvnw"
      ansible.builtin.set_fact:
        path_to_mvn: "{{ quarkus_app_workdir }}/{{ quarkus_app_source_folder | default('') }}/mvnw"

    - name: "Ensure that path to the mvn binary has been defined"
      ansible.builtin.assert:
        that:
          - path_to_mvn is defined and path_to_mvn | length > 0
        fail_msg: "Path to mvn is NOT defined or null or pointing to an unexisting file"

- name: "App build uses Maven directly (not mvnw)"
  when:
    - quarkus_use_mvnw is defined and not quarkus_use_mvnw
  block:
    - name: "Ensure required parameters are provided"
      ansible.builtin.assert:
        that:
          - quarkus_maven_download_url is defined and quarkus_maven_download_url | length > 0
          - quarkus_maven_homedir is defined and quarkus_maven_homedir | length > 0
        quiet: True
        fail_msg: "Can't ensure Maven is properly installed on quarkus_builder_host if quarkus_maven_download_url is not provided"

    - name: "Install Maven from {{ quarkus_maven_download_url }} on builder host [{{ quarkus_builder_host }}]"
      delegate_to: "{{ quarkus_builder_host }}"
      block:
        - name: "Ensure parent dir for Maven archive exists."
          ansible.builtin.file:
            path: "{{ quarkus_maven_homedir }}"
            state: directory

        - name: "Retrieve, if needed, archive from {{ quarkus_maven_download_url }}"
          ansible.builtin.unarchive:
            src: "{{ quarkus_maven_download_url }}"
            dest: "{{ quarkus_maven_homedir }}"
            remote_src: yes
            validate_certs: "{{ quarkus_maven_download_check_ssl }}"

        - name: "Set full path to mvnw"
          ansible.builtin.set_fact:
            path_to_mvn: "{{ quarkus_maven_homedir }}/{{ quarkus_maven_homedir_name }}/bin/mvn"

        - name: "Load metadata on {{ path_to_mvn }}"
          delegate_to: "{{ quarkus_builder_host }}"
          ansible.builtin.stat:
            path: "{{ path_to_mvn }}"
          register: stat_path_to_mvn

        - name: "Ensure that path to the mvn binary points to an existing file"
          ansible.builtin.assert:
            that:
              - stat_path_to_mvn is defined and stat_path_to_mvn.stat is defined
              - stat_path_to_mvn.stat.exists is defined and stat_path_to_mvn.stat.exists
            fail_msg: "Path to mvn points to an unexisting file"
