---
- name: "Ensure that the app port is accessible"
  ansible.builtin.wait_for:
    port: "{{ quarkus_app_port }}"
  when:
    - quarkus_app_port is defined
    - quarkus_app_port | length > 0

- name: "Ensure that webapp is reachable"
  ansible.builtin.get_url:
    url: "http://{{ quarkus_app_validation_host }}:{{ quarkus_app_port }}/"
    dest: '/dev/null'
  changed_when: false

- block:

    - name: "Populate service facts"
      ansible.builtin.service_facts:

    - name: "Ensure Quarkus app service is running: {{ quarkus_app_service_name }}"
      ansible.builtin.assert:
        that:
          - ansible_facts.services is defined
          - ansible_facts.services["{{ quarkus_app_service_name }}.service"] is defined
          - ansible_facts.services["{{ quarkus_app_service_name }}.service"]['status'] is defined
          - ansible_facts.services["{{ quarkus_app_service_name }}.service"]['status'] == 'enabled'
          - ansible_facts.services["{{ quarkus_app_service_name }}.service"]['state'] is defined
          - ansible_facts.services["{{ quarkus_app_service_name }}.service"]['state'] == 'running'
        quiet: true
  when:
    - quarkus_app_service_name is defined
