---
- name: Validation
  hosts: all
  tasks:
    - name: "Verify that Quarkus app is deployed properly."
      ansible.builtin.include_role:
        name: quarkus
        tasks_from: validate_deployment.yml
      vars:
        quarkus_app_validation_paths:
          - { path: 'hello/greeting/Bob' }
