---
quarkus_builder_host: localhost
quarkus_build_app: true
quarkus_build_delete_workdir: true
quarkus_build_shell_interpreter: /bin/bash
quarkus_build_relative_path_to_deploy_dir: target/quarkus-app/
quarkus_java_package_version: 'java-17-openjdk'
quarkus_java_home: '/usr/lib/jvm/jre-17-openjdk'

quarkus_app_workdir: '/tmp/workdir'
quarkus_app_user: quarkus_app
quarkus_app_group: "{{ quarkus_app_user }}"

quarkus_app_service_name: "{{ app_name }}"
quarkus_deploy_systemd_service_conf: "/etc/{{ app_name }}.conf"
quarkus_systemd_service_template: 'templates/service_systemd.j2'
quarkus_systemd_home: '/usr/lib/systemd/system'

quarkus_app_ports:
  - 8080
