---
quarkus_builder_host: localhost
quarkus_build_app: true
quarkus_build_delete_workdir: false
quarkus_build_check_workdir: true
quarkus_build_shell_interpreter: /bin/bash
quarkus_build_relative_path_to_deploy_dir: target/quarkus-app/

quarkus_java_version: 17
quarkus_java_package_version: "java-{{ quarkus_java_version }}-openjdk-devel"
quarkus_java_home: "/usr/lib/jvm/java-{{ quarkus_java_version }}-openjdk"
quarkus_java_home_isdir: False
quarkus_java_home_islnk: True

quarkus_use_mvnw: True
quarkus_maven_install: True
quarkus_maven_version: 3.9.8
quarkus_maven_download_url: "https://dlcdn.apache.org/maven/maven-3/{{ quarkus_maven_version }}/binaries/apache-maven-{{ quarkus_maven_version }}-bin.tar.gz"
quarkus_maven_homedir: /opt/apache/maven
quarkus_maven_homedir_name: "apache-maven-{{ quarkus_maven_version }}"
quarkus_maven_homedir_requires_privileges: yes
quarkus_maven_homedir_user: root
quarkus_maven_download_check_ssl: True
quarkus_maven_build_opts: ''

quarkus_app_workdir: '/tmp/workdir'
quarkus_app_dir_requires_become: yes
quarkus_app_dir_become_user: root
quarkus_app_user: quarkus_app
quarkus_app_group: "{{ quarkus_app_user }}"
quarkus_app_src_dir_remote: true

quarkus_app_builder_user_requires_become: true
quarkus_app_builder_skip_install_java_package: false
quarkus_app_builder_user: root
quarkus_app_builder_group: root

quarkus_deploy_app: True
quarkus_deploy_app_as_systemd_service_requires_privilege_escalation: True
quarkus_app_service_name: "{{ app_name }}"
quarkus_deploy_systemd_service_env_conf: "/etc/{{ app_name }}.conf"
quarkus_deploy_systemd_service_env_template: templates/service_env.j2
quarkus_deploy_systemd_daemon_reload_requires_become: yes
quarkus_deploy_systemd_daemon_reload_become_user: root
quarkus_deploy_skip_java_package_install: False
quarkus_path_to_folder_to_deploy_requires_become: yes
quarkus_path_to_folder_to_deploy_become_user: root
quarkus_app_validation_host: localhost
quarkus_systemd_service_template: 'templates/service_systemd.j2'
quarkus_systemd_home: '/usr/lib/systemd/system'

quarkus_app_port: 8080
quarkus_app_port_firewalld: "{{ quarkus_app_port }}"
quarkus_app_firewalld_enabled: false
quarkus_firewalld_package: firewalld
